### ISSUE TITLE
OAUTH_REQUEST_FAILED

### ISSUE THREAD

**Issue by ChristianVaughn** [jaycdev/lucia-azuread-prisma-example#1]
Hi, I stumbled upon your repo trying to debug my own project with Lucia Azure AD, and when trying your example, I am getting an OAuthRequestError: OAUTH_REQUEST_FAILED when the callback endpoint is trying to run. the status text of the error is just Bad Request. I was wondering if you had to setup your azure project in a special way to get the login working?

**Comment by jaycdev** [comment]
Hi mate, 

I just tested it out with a stock Azure AD app (web re-direct url is set to _http://localhost:3000/login/azure-ad/callback/_ with everything else as default) as it has been awhile and it seems like the problem is to do with the **hashed_password** column missing in the Key model of the prisma schema.

Edit your schema so that it has an optional hashed_password string in it

```ts
model Key {
  id              String  @id @unique
  user_id         String
  user            User    @relation(references: [id], fields: [user_id], onDelete: Cascade)

  @@index([user_id])
}
```

becomes

```ts
model Key {
  id              String  @id @unique
  user_id         String
  user            User    @relation(references: [id], fields: [user_id], onDelete: Cascade)
  hashed_password String?

  @@index([user_id])
}
```

That should fix it. Thanks!

**Comment by ChristianVaughn** [comment]
Yeah i had already had that added in. Thanks for the idea though. must just be something with my Azure AD/Microsoft Entra setup since i still get errors. will close the issue since it seems just to be on my end.
